name: dbt_instance
version: '0.1'
profile: dbt_instance
config-version: 2
model-paths:
  - models
analysis-paths:
  - analysis
test-paths:
  - tests
seed-paths:
  - data
macro-paths:
  - macros
target-path: target
clean-targets:
  - target
  - dbt_modules
  - logs
models:
  dbt_instance:
    materialized: table
    staging:
      materialized: view
seeds:
  dbt_instance:
    raw_customers:
      +column_types:
        created: timestamp
    raw_plan:
      +column_types:
        metadata: jsonb
    raw_tracks:
      +column_types:
        timestamp: timestamp
